#! /usr/bin/env python3

# Andrew Payne, info(*t)duckbrainsoftware(d*t)com

# Software Data:
soft_name = "ADM"
soft_tag  = "a simple desktop manager"

# Version
soft_vers = "beta 0.42"

import datetime
import getpass
import os
import shutil
import socket
import subprocess

# Colors
W = '\033[0m'  # white
O = '\033[33m' # orange

# Lists  
wm_sort   = []
wm_print  = []
wm_choose = []

# Locations
user_home   = os.environ['HOME']
xinitrc_dir = os.path.join('/etc/X11/xinit')

# Variables
key = 1
user_num = ''

for wm in os.listdir(os.path.join("/etc/X11/xinit/")):
    if os.path.isfile(os.path.join("/etc/X11/xinit/", wm)):
        if wm.startswith('xinitrc') and len(wm) > 8:
            wm_sort.append(wm)
            wm_sort.sort()

for wm in wm_sort:
    wm_print.append("\t\t\t")
    wm_print.append("[")
    wm_print.append(key)
    wm_print.append("]")
    wm_print.append(" ")
    wm_print.append(wm.split('.')[1])
    wm_print.append("\n")
    key += 1
    wm_choose.append(wm)

os.system('clear')
getsize = shutil.get_terminal_size()
col,line = getsize
for i in range(int(round(line/8))):
    print(" ".center(col))
print("\t\t\t-----------------------------------------------------------")
welstr = ("Welcome to " + O+ soft_name +W + " version " + soft_vers + ", " + soft_tag + ".")
print("\t\t\t" + welstr)
print("\n")
date = datetime.datetime.now().strftime("%_I:%M%P on %a, %b %w %Y.")
datestr = ("It is " + date)
print("\t\t\t" + datestr)
youstr = ("You are logged in as " + getpass.getuser() + " on " + socket.gethostname() + ".")
print("\n")
print("\t\t\t" + youstr)
print("\t\t\t-----------------------------------------------------------")
herestr = ("Here are the window managers found on your system...")
print("\n")
print("\t\t\t" + herestr)
print("\n")
print(''.join(map(str, wm_print)))
while user_num != 0 :
    user_num = input("\t\t\t(Q) to quit, or enter a number: ")
    if user_num == 'Q' or user_num == 'q':
        os.system('clear')
        break
    else:
        try:
            x = int(user_num) - 1
            winman = (wm_choose[x])
            user_uid  = os.getuid()
            group_gid = os.getgid()
## COMMENT OUT LINES 86 AND 87 TO DISABLE SAFETY BACKUP COPY
            if os.path.isfile(os.path.join(user_home, '.xinitrc')):
                shutil.move(os.path.join(user_home, '.xinitrc'), os.path.join(user_home, '.xinitrc_LAST'))
            shutil.copy2(os.path.join(xinitrc_dir, winman), os.path.join(user_home, '.xinitrc'))
            os.chown(os.path.join(user_home, '.xinitrc'), user_uid, group_gid)
            user_num = 0
            subprocess.run('startx')

        except ValueError:
            print(user_num + " is not an option")
            user_num=1
        except IndexError:
            print(user_num + " is not an option")
            user_num=1
