.\" Manpage for adm.
.\" Contact info@duckbrainsoftware.com.
.TH man 8 "26 June 2020" "1.0" "adm man page"
.SH NAME
adm \- a simple display manager 
.SH SYNOPSIS
adm
.SH DESCRIPTION
adm is a cli display manager.
.SH OPTIONS
There are no flags or options to set currently.
.SH SEE ALSO
There are no see also programs
.SH BUGS
They're in there somewhere.
.SH AUTHOR
Andrew Payne (info@duckbrainsoftware.com)
